[package]
name = "rust_os"
version = "0.1.0"
authors = ["hunterlester <guilfordhunter@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.8.0"

[package.metadata.bootimage]
default-target = "x86_64-target_config.json"
